import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import { StoreProvider } from "@/store/StoreProvider";
import { QueryProvider } from "./QueryProvider";
import { Toaster } from "react-hot-toast";

// Use className for full compatibility
const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased dark`}>
        <QueryProvider>
          <StoreProvider>
            <Header />
            <Toaster />
            {children}
          </StoreProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
